### ISSUE TITLE
I followed someone using this client and lost all my contacts

### ISSUE THREAD

**Issue by bitcoinuser** [digi-monkey/flycat-web#31]
Hi,

This client promises but I followed someone using this client and then the list of people I was following was erased.

**Comment by digi-monkey** [comment]
I am very sorry for that. 

sometimes the following list didn't refresh and this is a known bug. I will try roll out a recover fix. before that, you can use other clients to recover your history following.

**Comment by digi-monkey** [comment]
- https://github.com/digi-monkey/flycat-web/pull/34

@bitcoinuser just push a simple fix for this. if 0 followings bugs happen again, flycat will ask you to confirm before submitting. 

I also add a temp way to recovery the old followings, if you are sign-in, you will see a `history followings` in your contact page(click the Contact menu on leftSide to get there), you can click `recovery` to re-sign the old followings and broadcast to relays. Some relays are deleting the old-followings events, since flycat does not storing ANY data of users,  if you can't find any, we can only rely on relays so maybe just add more relays to try if anyone does have old following datas.

**Comment by digi-monkey** [comment]
should not be happening after this patch. so I am closing it. if you have any problems feel free to reopen it
